before_script:
  - 'git clone https://github.com/also/simpleserver.git'
  - 'ln -s simpleserver/config.ru .'
  - 'BUNDLE_GEMFILE=simpleserver/Gemfile bundle install'
  - 'BUNDLE_GEMFILE=simpleserver/Gemfile bundle exec rackup &'
  - 'sleep 3'
  - npm install

script:
  - grunt
  - phantomjs build/test/phantom.js
  - node build/test/run_node.js

rvm:
  - "1.9.3"
